#!/bin/sh

#cd /Users/bogao/sync/sydPage/src
echo "go build..."
echo "-200- go install github.com/elivoa/gxl..."
# go install github.com/elivoa/gxl

echo "-210- go install github.com/elivoa/got..."
# go install github.com/elivoa/got

echo "-210- go install github.com/elivoa/got/db..."
go install github.com/elivoa/got/db

echo "-250- go install got..."
go install got

echo "-260- go install syd..."
go install syd

# How to generate all components and pages package to build.
go install generated

echo "--- all done ---"
