#!/bin/sh

#cd /Users/bogao/sync/sydPage/src
echo "go build..."
echo "remove some folder first:"
rm -rf ~/develop/go/pkg/github.com/elivoa/got/builtin
rm -rf ~/develop/go/pkg/github.com/elivoa/got

echo "-200- go install github.com/elivoa/gxl..."
go install github.com/elivoa/gxl

echo "-210- go install github.com/elivoa/got..."
go install github.com/elivoa/got
go install github.com/elivoa/got/parser

echo "-210- go install github.com/elivoa/got/db..."
go install github.com/elivoa/got/db
go install github.com/elivoa/got/route
go install github.com/elivoa/got/errorhandler
go install github.com/elivoa/got/builtin/pages
go install github.com/elivoa/got/builtin/pages/got  
go install github.com/elivoa/got/builtin/components
go install github.com/elivoa/got/builtin/components/got          
go install github.com/elivoa/got/builtin/services 

echo "-250- go install got..."
go install got

echo "-260- go install syd..."
go install syd
go install syd/service
go install syd/model
go install syd/dal/userdao


# How to generate all components and pages package to build.
go install generated

# go install syd/components
# go install syd/pages
# go install syd/dal
# go install syd/model

echo "-270- go run main.go..."

echo "---------------------------------------------------------------------------------------------------"
go run main.go
